// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ban.sql

package sqlc

import (
	"context"
	"time"
)

const deleteBan = `-- name: DeleteBan :exec
DELETE FROM banned_peers
WHERE ip_net = $1
`

func (q *Queries) DeleteBan(ctx context.Context, ipNet []byte) error {
	_, err := q.db.ExecContext(ctx, deleteBan, ipNet)
	return err
}

const deleteExpiredBans = `-- name: DeleteExpiredBans :execrows
DELETE FROM banned_peers
WHERE expiration <= $1
`

func (q *Queries) DeleteExpiredBans(ctx context.Context, expiration time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredBans, expiration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBan = `-- name: GetBan :one
SELECT expiration, reason FROM banned_peers
WHERE ip_net = $1
`

type GetBanRow struct {
	Expiration time.Time
	Reason     int32
}

func (q *Queries) GetBan(ctx context.Context, ipNet []byte) (GetBanRow, error) {
	row := q.db.QueryRowContext(ctx, getBan, ipNet)
	var i GetBanRow
	err := row.Scan(&i.Expiration, &i.Reason)
	return i, err
}

const upsertBan = `-- name: UpsertBan :exec
INSERT INTO banned_peers (ip_net, expiration, reason)
VALUES ($1, $2, $3)
ON CONFLICT (ip_net) DO UPDATE
SET expiration = excluded.expiration,
    reason     = excluded.reason
`

type UpsertBanParams struct {
	IpNet      []byte
	Expiration time.Time
	Reason     int32
}

func (q *Queries) UpsertBan(ctx context.Context, arg UpsertBanParams) error {
	_, err := q.db.ExecContext(ctx, upsertBan, arg.IpNet, arg.Expiration, arg.Reason)
	return err
}
