// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chain_tips.sql

package sqlc

import (
	"context"
)

const deleteChainTip = `-- name: DeleteChainTip :exec
DELETE FROM chain_tips
WHERE chain_type = $1
`

func (q *Queries) DeleteChainTip(ctx context.Context, chainType int32) error {
	_, err := q.db.ExecContext(ctx, deleteChainTip, chainType)
	return err
}

const getChainTip = `-- name: GetChainTip :one
SELECT tip_hash, tip_height FROM chain_tips
WHERE chain_type = $1
`

type GetChainTipRow struct {
	TipHash   []byte
	TipHeight int64
}

func (q *Queries) GetChainTip(ctx context.Context, chainType int32) (GetChainTipRow, error) {
	row := q.db.QueryRowContext(ctx, getChainTip, chainType)
	var i GetChainTipRow
	err := row.Scan(&i.TipHash, &i.TipHeight)
	return i, err
}

const upsertChainTip = `-- name: UpsertChainTip :exec
INSERT INTO chain_tips (chain_type, tip_hash, tip_height, updated_at)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
ON CONFLICT (chain_type) DO UPDATE
SET tip_hash   = excluded.tip_hash,
    tip_height = excluded.tip_height,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertChainTipParams struct {
	ChainType int32
	TipHash   []byte
	TipHeight int64
}

func (q *Queries) UpsertChainTip(ctx context.Context, arg UpsertChainTipParams) error {
	_, err := q.db.ExecContext(ctx, upsertChainTip, arg.ChainType, arg.TipHash, arg.TipHeight)
	return err
}
