// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fee_samples.sql

package sqlc

import (
	"context"
)

const deleteFeeSamplesBeforeHeight = `-- name: DeleteFeeSamplesBeforeHeight :exec
DELETE FROM fee_samples
WHERE height < $1
`

func (q *Queries) DeleteFeeSamplesBeforeHeight(ctx context.Context, height int64) error {
	_, err := q.db.ExecContext(ctx, deleteFeeSamplesBeforeHeight, height)
	return err
}

const deleteFeeSamplesFromHeight = `-- name: DeleteFeeSamplesFromHeight :exec
DELETE FROM fee_samples
WHERE height >= $1
`

func (q *Queries) DeleteFeeSamplesFromHeight(ctx context.Context, height int64) error {
	_, err := q.db.ExecContext(ctx, deleteFeeSamplesFromHeight, height)
	return err
}

const getFeeSampleByHeight = `-- name: GetFeeSampleByHeight :one
SELECT height, block_hash, timestamp, total_fees, total_weight, coinbase_weight, min_known_tx_rate, known_tx_count, flags FROM fee_samples
WHERE height = $1
`

func (q *Queries) GetFeeSampleByHeight(ctx context.Context, height int64) (FeeSample, error) {
	row := q.db.QueryRowContext(ctx, getFeeSampleByHeight, height)
	var i FeeSample
	err := row.Scan(
		&i.Height,
		&i.BlockHash,
		&i.Timestamp,
		&i.TotalFees,
		&i.TotalWeight,
		&i.CoinbaseWeight,
		&i.MinKnownTxRate,
		&i.KnownTxCount,
		&i.Flags,
	)
	return i, err
}

const getFeeSampleRange = `-- name: GetFeeSampleRange :many
SELECT height, block_hash, timestamp, total_fees, total_weight, coinbase_weight, min_known_tx_rate, known_tx_count, flags FROM fee_samples
WHERE height BETWEEN $1 AND $2
ORDER BY height ASC
`

type GetFeeSampleRangeParams struct {
	StartHeight int64
	EndHeight   int64
}

func (q *Queries) GetFeeSampleRange(ctx context.Context, arg GetFeeSampleRangeParams) ([]FeeSample, error) {
	rows, err := q.db.QueryContext(ctx, getFeeSampleRange, arg.StartHeight, arg.EndHeight)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeeSample
	for rows.Next() {
		var i FeeSample
		if err := rows.Scan(
			&i.Height,
			&i.BlockHash,
			&i.Timestamp,
			&i.TotalFees,
			&i.TotalWeight,
			&i.CoinbaseWeight,
			&i.MinKnownTxRate,
			&i.KnownTxCount,
			&i.Flags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeeSampleTip = `-- name: GetFeeSampleTip :one
SELECT CAST(COALESCE(MAX(height), 0) AS BIGINT) AS tip FROM fee_samples
`

func (q *Queries) GetFeeSampleTip(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFeeSampleTip)
	var tip int64
	err := row.Scan(&tip)
	return tip, err
}

const getFeeSamplesTipN = `-- name: GetFeeSamplesTipN :many
SELECT height, block_hash, timestamp, total_fees, total_weight, coinbase_weight, min_known_tx_rate, known_tx_count, flags FROM fee_samples
ORDER BY height DESC
LIMIT $1
`

func (q *Queries) GetFeeSamplesTipN(ctx context.Context, limit int32) ([]FeeSample, error) {
	rows, err := q.db.QueryContext(ctx, getFeeSamplesTipN, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeeSample
	for rows.Next() {
		var i FeeSample
		if err := rows.Scan(
			&i.Height,
			&i.BlockHash,
			&i.Timestamp,
			&i.TotalFees,
			&i.TotalWeight,
			&i.CoinbaseWeight,
			&i.MinKnownTxRate,
			&i.KnownTxCount,
			&i.Flags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeeSample = `-- name: UpsertFeeSample :exec
INSERT INTO fee_samples (
    height, block_hash, timestamp, total_fees, total_weight,
    coinbase_weight, min_known_tx_rate, known_tx_count, flags
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (height) DO UPDATE
SET block_hash        = excluded.block_hash,
    timestamp         = excluded.timestamp,
    total_fees        = excluded.total_fees,
    total_weight      = excluded.total_weight,
    coinbase_weight   = excluded.coinbase_weight,
    min_known_tx_rate = excluded.min_known_tx_rate,
    known_tx_count    = excluded.known_tx_count,
    flags             = excluded.flags
`

type UpsertFeeSampleParams struct {
	Height         int64
	BlockHash      []byte
	Timestamp      int64
	TotalFees      int64
	TotalWeight    int64
	CoinbaseWeight int64
	MinKnownTxRate int64
	KnownTxCount   int32
	Flags          int32
}

func (q *Queries) UpsertFeeSample(ctx context.Context, arg UpsertFeeSampleParams) error {
	_, err := q.db.ExecContext(ctx, upsertFeeSample,
		arg.Height,
		arg.BlockHash,
		arg.Timestamp,
		arg.TotalFees,
		arg.TotalWeight,
		arg.CoinbaseWeight,
		arg.MinKnownTxRate,
		arg.KnownTxCount,
		arg.Flags,
	)
	return err
}
