// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: filters.sql

package sqlc

import (
	"context"
)

const getFilter = `-- name: GetFilter :one
SELECT filter_bytes FROM regular_filters
WHERE block_hash = $1
`

func (q *Queries) GetFilter(ctx context.Context, blockHash []byte) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getFilter, blockHash)
	var filter_bytes []byte
	err := row.Scan(&filter_bytes)
	return filter_bytes, err
}

const purgeRegularFilters = `-- name: PurgeRegularFilters :exec
DELETE FROM regular_filters
`

func (q *Queries) PurgeRegularFilters(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, purgeRegularFilters)
	return err
}

const putFilter = `-- name: PutFilter :exec
INSERT INTO regular_filters (block_hash, filter_bytes)
VALUES ($1, $2)
ON CONFLICT (block_hash) DO UPDATE
SET filter_bytes = excluded.filter_bytes
`

type PutFilterParams struct {
	BlockHash   []byte
	FilterBytes []byte
}

func (q *Queries) PutFilter(ctx context.Context, arg PutFilterParams) error {
	_, err := q.db.ExecContext(ctx, putFilter, arg.BlockHash, arg.FilterBytes)
	return err
}
