// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: filter_headers.sql

package sqlc

import (
	"context"
)

const countFilterHeaders = `-- name: CountFilterHeaders :one
SELECT COUNT(*) FROM filter_headers
`

func (q *Queries) CountFilterHeaders(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFilterHeaders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFilterHeadersFromHeight = `-- name: DeleteFilterHeadersFromHeight :exec
DELETE FROM filter_headers
WHERE height > $1
`

func (q *Queries) DeleteFilterHeadersFromHeight(ctx context.Context, height int64) error {
	_, err := q.db.ExecContext(ctx, deleteFilterHeadersFromHeight, height)
	return err
}

const getFilterHeaderByBlockHash = `-- name: GetFilterHeaderByBlockHash :one
SELECT height, filter_hash FROM filter_headers
WHERE block_hash = $1
`

type GetFilterHeaderByBlockHashRow struct {
	Height     int64
	FilterHash []byte
}

func (q *Queries) GetFilterHeaderByBlockHash(ctx context.Context, blockHash []byte) (GetFilterHeaderByBlockHashRow, error) {
	row := q.db.QueryRowContext(ctx, getFilterHeaderByBlockHash, blockHash)
	var i GetFilterHeaderByBlockHashRow
	err := row.Scan(&i.Height, &i.FilterHash)
	return i, err
}

const getFilterHeaderByHeight = `-- name: GetFilterHeaderByHeight :one
SELECT block_hash, filter_hash FROM filter_headers
WHERE height = $1
`

type GetFilterHeaderByHeightRow struct {
	BlockHash  []byte
	FilterHash []byte
}

func (q *Queries) GetFilterHeaderByHeight(ctx context.Context, height int64) (GetFilterHeaderByHeightRow, error) {
	row := q.db.QueryRowContext(ctx, getFilterHeaderByHeight, height)
	var i GetFilterHeaderByHeightRow
	err := row.Scan(&i.BlockHash, &i.FilterHash)
	return i, err
}

const getFilterHeaderRange = `-- name: GetFilterHeaderRange :many
SELECT height, block_hash, filter_hash FROM filter_headers
WHERE height BETWEEN $1 AND $2
ORDER BY height ASC
`

type GetFilterHeaderRangeParams struct {
	StartHeight int64
	EndHeight   int64
}

func (q *Queries) GetFilterHeaderRange(ctx context.Context, arg GetFilterHeaderRangeParams) ([]FilterHeader, error) {
	rows, err := q.db.QueryContext(ctx, getFilterHeaderRange, arg.StartHeight, arg.EndHeight)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilterHeader
	for rows.Next() {
		var i FilterHeader
		if err := rows.Scan(&i.Height, &i.BlockHash, &i.FilterHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFilterHeader = `-- name: InsertFilterHeader :exec
INSERT INTO filter_headers (height, block_hash, filter_hash)
VALUES ($1, $2, $3)
`

type InsertFilterHeaderParams struct {
	Height     int64
	BlockHash  []byte
	FilterHash []byte
}

func (q *Queries) InsertFilterHeader(ctx context.Context, arg InsertFilterHeaderParams) error {
	_, err := q.db.ExecContext(ctx, insertFilterHeader, arg.Height, arg.BlockHash, arg.FilterHash)
	return err
}

const purgeFilterHeaders = `-- name: PurgeFilterHeaders :exec
DELETE FROM filter_headers
`

func (q *Queries) PurgeFilterHeaders(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, purgeFilterHeaders)
	return err
}
