// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: headers.sql

package sqlc

import (
	"context"
)

const countBlockHeaders = `-- name: CountBlockHeaders :one
SELECT COUNT(*) FROM block_headers
`

func (q *Queries) CountBlockHeaders(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBlockHeaders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBlockHeadersFromHeight = `-- name: DeleteBlockHeadersFromHeight :exec
DELETE FROM block_headers
WHERE height > $1
`

func (q *Queries) DeleteBlockHeadersFromHeight(ctx context.Context, height int64) error {
	_, err := q.db.ExecContext(ctx, deleteBlockHeadersFromHeight, height)
	return err
}

const getBlockHeaderByHash = `-- name: GetBlockHeaderByHash :one
SELECT height, raw_header FROM block_headers
WHERE block_hash = $1
`

type GetBlockHeaderByHashRow struct {
	Height    int64
	RawHeader []byte
}

func (q *Queries) GetBlockHeaderByHash(ctx context.Context, blockHash []byte) (GetBlockHeaderByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getBlockHeaderByHash, blockHash)
	var i GetBlockHeaderByHashRow
	err := row.Scan(&i.Height, &i.RawHeader)
	return i, err
}

const getBlockHeaderByHeight = `-- name: GetBlockHeaderByHeight :one
SELECT raw_header FROM block_headers
WHERE height = $1
`

func (q *Queries) GetBlockHeaderByHeight(ctx context.Context, height int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getBlockHeaderByHeight, height)
	var raw_header []byte
	err := row.Scan(&raw_header)
	return raw_header, err
}

const getBlockHeaderHeightByHash = `-- name: GetBlockHeaderHeightByHash :one
SELECT height FROM block_headers
WHERE block_hash = $1
`

func (q *Queries) GetBlockHeaderHeightByHash(ctx context.Context, blockHash []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBlockHeaderHeightByHash, blockHash)
	var height int64
	err := row.Scan(&height)
	return height, err
}

const getBlockHeaderRange = `-- name: GetBlockHeaderRange :many
SELECT height, raw_header FROM block_headers
WHERE height BETWEEN $1 AND $2
ORDER BY height ASC
`

type GetBlockHeaderRangeParams struct {
	StartHeight int64
	EndHeight   int64
}

type GetBlockHeaderRangeRow struct {
	Height    int64
	RawHeader []byte
}

func (q *Queries) GetBlockHeaderRange(ctx context.Context, arg GetBlockHeaderRangeParams) ([]GetBlockHeaderRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getBlockHeaderRange, arg.StartHeight, arg.EndHeight)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlockHeaderRangeRow
	for rows.Next() {
		var i GetBlockHeaderRangeRow
		if err := rows.Scan(&i.Height, &i.RawHeader); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBlockHeader = `-- name: InsertBlockHeader :exec
INSERT INTO block_headers (height, block_hash, raw_header)
VALUES ($1, $2, $3)
`

type InsertBlockHeaderParams struct {
	Height    int64
	BlockHash []byte
	RawHeader []byte
}

func (q *Queries) InsertBlockHeader(ctx context.Context, arg InsertBlockHeaderParams) error {
	_, err := q.db.ExecContext(ctx, insertBlockHeader, arg.Height, arg.BlockHash, arg.RawHeader)
	return err
}
