// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type BannedPeer struct {
	ID         int32
	IpNet      []byte
	Expiration time.Time
	Reason     int32
}

type BlockHeader struct {
	Height    int64
	BlockHash []byte
	RawHeader []byte
}

type ChainTip struct {
	ChainType int32
	TipHash   []byte
	TipHeight int64
	UpdatedAt time.Time
}

type FilterHeader struct {
	Height     int64
	BlockHash  []byte
	FilterHash []byte
}

type RegularFilter struct {
	BlockHash   []byte
	FilterBytes []byte
}
