// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"time"
)

type Querier interface {
	CountBlockHeaders(ctx context.Context) (int64, error)
	CountFilterHeaders(ctx context.Context) (int64, error)
	DeleteBan(ctx context.Context, ipNet []byte) error
	DeleteBlockHeadersFromHeight(ctx context.Context, height int64) error
	DeleteChainTip(ctx context.Context, chainType int32) error
	DeleteExpiredBans(ctx context.Context, expiration time.Time) (int64, error)
	DeleteFilterHeadersFromHeight(ctx context.Context, height int64) error
	GetBan(ctx context.Context, ipNet []byte) (GetBanRow, error)
	GetBlockHeaderByHash(ctx context.Context, blockHash []byte) (GetBlockHeaderByHashRow, error)
	GetBlockHeaderByHeight(ctx context.Context, height int64) ([]byte, error)
	GetBlockHeaderHeightByHash(ctx context.Context, blockHash []byte) (int64, error)
	GetBlockHeaderRange(ctx context.Context, arg GetBlockHeaderRangeParams) ([]GetBlockHeaderRangeRow, error)
	GetChainTip(ctx context.Context, chainType int32) (GetChainTipRow, error)
	GetFilter(ctx context.Context, blockHash []byte) ([]byte, error)
	GetFilterHeaderByBlockHash(ctx context.Context, blockHash []byte) (GetFilterHeaderByBlockHashRow, error)
	GetFilterHeaderByHeight(ctx context.Context, height int64) (GetFilterHeaderByHeightRow, error)
	GetFilterHeaderRange(ctx context.Context, arg GetFilterHeaderRangeParams) ([]FilterHeader, error)
	InsertBlockHeader(ctx context.Context, arg InsertBlockHeaderParams) error
	InsertFilterHeader(ctx context.Context, arg InsertFilterHeaderParams) error
	PurgeFilterHeaders(ctx context.Context) error
	PurgeRegularFilters(ctx context.Context) error
	PutFilter(ctx context.Context, arg PutFilterParams) error
	UpsertBan(ctx context.Context, arg UpsertBanParams) error
	UpsertChainTip(ctx context.Context, arg UpsertChainTipParams) error
}

var _ Querier = (*Queries)(nil)
