version: "2"
linters:
  default: all
  disable:
    - containedctx
    - contextcheck
    # Disable complexity linters.
    - cyclop
    - depguard
    - dogsled
    - err113
    - errname
    # Causes stack overflow, see https://github.com/polyfloyd/go-errorlint/issues/19.
    - errorlint
    - exhaustive
    - exhaustruct
    - forcetypeassert
    # We have long functions, especially in tests.
    - funlen
    # Global variables are used in many places throughout the codebase.
    - gochecknoglobals
    # Init functions are used by loggers throughout the codebase.
    - gochecknoinits
    - gocognit
    - gocyclo
    # We want to allow TODOs.
    - godox
    - gomoddirectives
    - inamedparam
    - intrange
    - ireturn
    - maintidx
    - mnd
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - perfsprint
    # Instances of table driven tests that don't pre-allocate shouldn't trigger the linter.
    - prealloc
    - recvcheck
    - revive
    - testpackage
    - thelper
    - tparallel
    # We want to allow short variable names.
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    gosec:
      excludes:
        - G115
    lll:
      line-length: 80
      tab-width: 8
    whitespace:
      multi-if: true
      multi-func: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gosec
          - prealloc
          - staticcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  new-from-rev: c932ae495eeedc20f58a521d0b3e08889348b06c
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
